### PR TITLE
Added Github repo to concept page

### PR DESCRIPTION
**Pull request by LanceALaughlin**
Is this how we should be doing this or do you want us to push directly to your repo?

### CODE REVIEW

**Comment by Nolski** [comment]
I would say if we are all developing on this game then we should not do pull requests. Instead if you are working on a feature that might break the application, create a branch and then we will merge it when it's finished.

**Comment by LanceALaughlin** [comment]
Okay, I wasn't sure the best way to do everything since my only GitHub experience has been this class thus far. I'll keep that in mind in the future. So should I just push directly to the main repo then?

**Comment by Nolski** [comment]
Yeah, just git push origin master. I can show you (and anyone else who might be interested) at a later.

**Comment by LanceALaughlin** [comment]
That would be great! Thanks!

**Pull request merged**
